### ISSUE TITLE
Consider licence change

### ISSUE THREAD

**Issue by bruce34** [erning/gorun#14]
Would it be possible to move away from the GPLv3 to a more permissive licence, e.g. MIT or similar?
Within a company environment, having to think about GPLv3 (and explain it to co-workers) means we are much less likely to pick up the tool, use it, hack on it and contribute back.

**Comment by NightMachinery** [comment]
[**@bruce34**](https://github.com/bruce34) commented on [Feb 25, 2020, 8:12 PM GMT+3:30](https://github.com/erning/gorun/issues/14#issue-570690703 "2020-02-25T16:42:03Z - Replied by Github Reply Comments"):
> Would it be possible to move away from the GPLv3 to a more permissive licence, e.g. MIT or similar?  
> Within a company environment, having to think about GPLv3 (and explain it to co-workers) means we are much less likely to pick up the tool, use it, hack on it and contribute back.

This is by design.

**Comment by bruceadam-tomtom** [comment]
Fair enough. The GPLv3 was just too restrictive for us in this case, so I've rewritten the chunks you did in my repo https://github.com/bruce34/gorun with an Apache 2 licence. That is where we'll continue development of the binary within our organisation. I'll still push out changes to that repo in case they are of interest to others.

Thanks for the original idea and considering the question :)
