### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by bryaan** [erning/gorun#24]
How do I install this library?  It should be added to readme.

**Comment by tech10** [comment]
Here is a quick example of installation commands to help you get started. Sudo is required for this to work completely, so far as installing the binary into the main bin directory goes.

```console
$ git clone https://github.com/erning/gorun
$ cd ./gorun
$ go build .
$ sudo mv ./gorun /usr/bin/
```

You can of course replace the mv command with any location you desire, such as something like this.

```console
$ mv ./gorun ~/bin/
```

If you use that example, you'll need $HOME/bin in your path in order for this to work properly.

At the moment there aren't any pre-compiled binaries available for download, nor are there packages for many platforms but the Ubuntu ones in the readme, presuming they are still available.

I hope this helps, good luck.

**Comment by bryaan** [comment]
@tech10 Thank you.
