### ISSUE TITLE
go get launchpad.net/gorun fetched old version

### ISSUE THREAD

**Issue by yangit** [erning/gorun#5]
`go get launchpad.net/gorun` fetched old version which does not compile on go v1.6
That is a bummer because https://wiki.ubuntu.com/gorun suggests to do just that and is first on google results.

**Comment by yangit** [comment]
I mean the version of `gorun` itself is compiling just fine. But it can't compile user scripts giving 

````
go tool: no such tool "6g"
error: failed to run go: exit status 3
````

**Comment by erning** [comment]
this repo is a fork from launchpad

**Comment by yangit** [comment]
Oh, I thought you was the owner of the both of them :)
