### ISSUE TITLE
Linux binfmt_misc

### ISSUE THREAD

**Issue by powerman** [erning/gorun#6]
It worth to mention Linux-specific way to run go scripts with help of binfmt_misc (run as root):

```sh
# copy or symlink gorun binary to /usr/local/bin/
echo -n ':go:M::package main\x0a::/usr/local/bin/gorun:' > /proc/sys/fs/binfmt_misc/register
```

Now we can create and run go scripts just like any other:

```sh
$ $EDITOR ~/bin/script.go
$ chmod +x ~/bin/script.go
$ script.go
```

Only limitation is we can't split that script into several files in same directory, but that's probably good thing anyway because simple scripts shouldn't need this and because in `~/bin/` there will be a lot of go script, each with `package main` and `function main() {}`, so adding helper go files needed for some of these scripts into the same directory isn't really good idea - such helpers should be moved to separate package(s).

Ideally we should use `.go` extension to detect files suitable to run, but gorun creates binaries in /tmp/ also with `.go` extension (which is probably isn't correct and good idea anyway), so when using `.go` extension to setup binfmt_misc instead of magic `package main\n` we get error because binaries compiled by gorun also executed using gorun because of their `.go` extension. Maybe you'll fix this (change extension for cached binaries from `.go` to anything else)?

**Comment by erning** [comment]
```diff
diff --git a/gorun.go b/gorun.go
index c34f61e..aa855cb 100644
--- a/gorun.go
+++ b/gorun.go
@@ -174,6 +174,7 @@ func RunFile(sourcefile string) (rundir, runfile string, err error) {
        runfile = strings.Replace(sourcefile, "%", "%%", -1)
        runfile = strings.Replace(runfile, string(filepath.Separator), "%", -1)
        runfile = filepath.Join(rundir, runfile)
+       runfile += ".gorun"
        return rundir, runfile, nil
 }
```
